apiVersion: apps/v1
kind: DeploymentCredential 생성시에는 Login ID, Password 로 생성합니다.
(Secret Text로 하면 Jenkins 버
metadata:
  name: hello-flask
  labels:
    app: hello-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-flask
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
      - name: flask-app
        image: 998902534284.dkr.ecr.ap-northeast-2.amazonaws.com/test-repository:IMAGE_VERSION
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-flask-service
spec:
  type: LoadBalancer
  selector:
    app: hello-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

